### PR TITLE
WIP: Update JSDoc type definitions

### PR DESCRIPTION
**Pull request by cameronhunter**
Hi! I was seeing type-errors on the object returned by `cfonts.render`:

Screen Shot 2019-07-04 at 16 52 39

In this pull-request I made a quick pass on the JSDoc types which should resolve this.

Thanks for making such a cool library 🙌

### CODE REVIEW

**Comment by dominikwilkowski** [comment]
Hey @cameronhunter 

Thanks for that. What tool are you using to parse jsDocs? I'd love to reproduce this on my end.

**Comment by cameronhunter** [comment]
I'm using VS Code with this setting enabled `"javascript.implicitProjectConfig.checkJs": true` ([blog post](https://medium.com/@trukrs/just-so-you-know-you-can-have-static-typing-in-javascript-using-jsdoc-and-typescript-5b2c6e9112dc)). With that setting enabled the IDE will use TypeScript to type-check JavaScript files and [TypeScript has support for parsing JSDoc comments](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html).

**Comment by dominikwilkowski** [comment]
Is there a way to extract the type definitions into their own files for ts? I'd rather not mix those. You open to having a look?

**Comment by cameronhunter** [comment]
You could have a `lib.d.ts` file that contained the same definitions as I put in the code, but you'd still want to import them into the JS file which doesn't really save anything.

I should note that these aren't explicitly TypeScript types, they're just JSDoc that TypeScript understands; we're not mixing worlds here.

**Comment by dominikwilkowski** [comment]
Got you.

The `/** @typedef {typeof COLORS} Colors */` comments everywhere make me nervous. I'll have a look into this. The jsDocs should at least be correct.

**Comment by cameronhunter** [comment]
We can remove those and just use `object`, I was added more than is strictly necessary 🙂

**Comment by dominikwilkowski** [comment]
No I think you're actually right with most of them. I just need some time to process :)
On vacation for two weeks now. Will look into this and merge when back.

**Comment by dominikwilkowski** [comment]
Hey @cameronhunter 

I've started to go through this PR and am not able to find `typeof` in the specs: https://jsdoc.app/
I gather it takes the variable and uses it to infer the types?
As I have no way to actually check any of the types I'm not sure I can be very helpful here.
I'm happy to put some effort in, just need some way to test the types. Is there a repl or some other thing online I can use?

**Comment by dominikwilkowski** [comment]
Hey @cameronhunter 

Thank you so much for this PR. It got me into fixing my messy jsDocs and I added now a type test via typescript to my test suite: https://github.com/dominikwilkowski/cfonts/blob/master/package.json#L38

You've done a lot of work in this PR which I went through and made sure to adopt as much as I could into the new file structure that was necessary for the new gradient work.
You also found a bunch of bugs:
- [typos](https://github.com/dominikwilkowski/cfonts/pull/21/files#diff-04c6e90faac2675aa89e2176d2eec7d8L275)
- [bad practise](https://github.com/dominikwilkowski/cfonts/pull/21/files#diff-66cf232fe18a3b1d72fd6204ad1447ecL490)
- [flat out bug](https://github.com/dominikwilkowski/cfonts/pull/21/files#diff-66cf232fe18a3b1d72fd6204ad1447ecL815)
- [code waste](https://github.com/dominikwilkowski/cfonts/pull/21/files#diff-66cf232fe18a3b1d72fd6204ad1447ecL1035-L1036)
- [missing declarations in jsDocs](https://github.com/dominikwilkowski/cfonts/pull/21/files#diff-66cf232fe18a3b1d72fd6204ad1447ecR1137-R1138)

So thanks again for your work. I have now published Cfonts v2.5.2 which should now have the correct types. I'd appreciate if you could check on your end and report back any issues.

I'll close this PR now as it's been merged into master today via bits and pieces.

**Comment by cameronhunter** [comment]
What a really nice message to receive. Thanks for all of your hard work – it's really appreciated!

**Pull request closed without merging**
