### PR TITLE
Add: top, bottom option for the "space" setting

### PR DESCRIPTION
**Pull request by abhijit-hota**
Making a draft cause I've still not tested it.

### CODE REVIEW

**Comment by dominikwilkowski** [comment]
Hey @abhijit-hota 
That's a great idea and all tests pass so that's a good thing. Let me have a look and give feedback if it's needed :)

**Comment by dominikwilkowski** [comment]
Thanks for this. Great idea.
I ended up moving the alignment options into `align` as it felt more appropriate and also played nicer with the type. Mixing a boolean with a keyword is hard and not exactly POSIX.
But I kept your commits and made changes to them. That way you get credit :D 

Merged now and will publish in `v2.9.0`

**Comment by abhijit-hota** [comment]
Thanks a lot! @dominikwilkowski 

> played nicer with the type. Mixing a boolean with a keyword is hard and not exactly POSIX.

Ah, I see.
A beginner(?) question though, if you have time. What does "not exactly POSIX" mean here? (I googled it up and only found out about the OS)

P.S. You might want to add an underscore at the end of line [here](https://github.com/dominikwilkowski/cfonts/tree/develop#-a---align):

> - `bottom` _(Will be ignored if used with the spaceless option)

**Comment by dominikwilkowski** [comment]
[POSIX](https://en.wikipedia.org/wiki/POSIX) is a standard for (amongst other things) CLI (Command Line Interfaces). It describes how we call `cfonts` in the shell and how you add arguments like boolean flags or options.
A good resource would be this document: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html

And thanks for the typo heads up. Just fixed that

**Comment by abhijit-hota** [comment]
Thank you for the pointers!

**Pull request merged**
